
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSystemTheme() : Promise<OscopeTheme> {
    return await TAURI_INVOKE("get_system_theme");
},
async getTitlebarLayout() : Promise<TitlebarLayout> {
    return await TAURI_INVOKE("get_titlebar_layout");
},
async getSerialStatus() : Promise<SerialStatus> {
    return await TAURI_INVOKE("get_serial_status");
},
async getCurrentFrame() : Promise<[FrontendFrameData, FrontendFrameData]> {
    return await TAURI_INVOKE("get_current_frame");
},
async receiveVerificationMessages(onEvent: TAURI_CHANNEL<VerificationMessage>) : Promise<void> {
    await TAURI_INVOKE("receive_verification_messages", { onEvent });
},
async sendVerificationMessage(message: VerificationMessage) : Promise<void> {
    await TAURI_INVOKE("send_verification_message", { message });
},
async sendChannelOptions(channelOptions: ChannelOptions) : Promise<void> {
    await TAURI_INVOKE("send_channel_options", { channelOptions });
},
async sendSampleRate(sampleRate: number) : Promise<void> {
    await TAURI_INVOKE("send_sample_rate", { sampleRate });
},
async sendCalibrationMessage(message: CalibrationMessage) : Promise<void> {
    await TAURI_INVOKE("send_calibration_message", { message });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
serialStatus: SerialStatus
}>({
serialStatus: "serial-status"
})

/** user-defined constants **/



/** user-defined types **/

export type CalibrationData = { channel: ScopeChannel; value: number }
export type CalibrationMessage = { CalibrateCenter: CalibrationData } | { CalibrateMax: CalibrationData } | { CalibrateMin: CalibrationData }
export type ChannelOptions = { channel: ScopeChannel; enabled: boolean; voltage_gain: ScopeGain; coupling: ScopeCoupling }
export type Color = { red: number; green: number; blue: number; alpha: number }
export type FrontendFrameData = { data: number[]; center: number; timestep_ms: number; voltage_scale: number; channel: ScopeChannel }
export type OscopeTheme = { primary: Color | null; primary_fg: Color | null; bg: Color | null; fg: Color | null; secondary: Color | null; secondary_fg: Color | null; ring: Color | null }
export type ScopeChannel = "A" | "B"
export type ScopeCoupling = "DC" | "AC"
export type ScopeGain = "One" | "Four" | "Twenty"
export type SerialStatus = "Connected" | "Disconnected"
export type TitlebarButton = "Menu" | "Minimize" | "Maximize" | "Close"
export type TitlebarLayout = { left: TitlebarButton[]; right: TitlebarButton[] }
export type VerificationMessage = { TriggerState: boolean } | "StartDacTest" | "SetGpioHigh" | "SetGpioLow"

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
