/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as SubpageRouteImport } from './routes/_subpage'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubpageTestRouteImport } from './routes/_subpage/test'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const SubpageRoute = SubpageRouteImport.update({
  id: '/_subpage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubpageTestRoute = SubpageTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => SubpageRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/test': typeof SubpageTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/test': typeof SubpageTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_subpage': typeof SubpageRouteWithChildren
  '/home': typeof HomeRoute
  '/_subpage/test': typeof SubpageTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/home' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/test'
  id: '__root__' | '/' | '/_subpage' | '/home' | '/_subpage/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubpageRoute: typeof SubpageRouteWithChildren
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_subpage': {
      id: '/_subpage'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SubpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_subpage/test': {
      id: '/_subpage/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof SubpageTestRouteImport
      parentRoute: typeof SubpageRoute
    }
  }
}

interface SubpageRouteChildren {
  SubpageTestRoute: typeof SubpageTestRoute
}

const SubpageRouteChildren: SubpageRouteChildren = {
  SubpageTestRoute: SubpageTestRoute,
}

const SubpageRouteWithChildren =
  SubpageRoute._addFileChildren(SubpageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubpageRoute: SubpageRouteWithChildren,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
